name: test

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Raku/setup-raku@v1
        with:
          raku-version: '2020.09'

      - name: Setup Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: .raku
          key: raku-${{ hashFiles('./META6.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p $GITHUB_WORKSPACE/.raku
          zef install \
              --install-to=inst#$GITHUB_WORKSPACE/.raku \
              --debug \
              --deps-only \
              --/test \
              --test-depends \
              .

      - name: Run Tests
        run: |
          RAKULIB=inst#$GITHUB_WORKSPACE/.raku $GITHUB_WORKSPACE/.raku/bin/prove6 -v -l t
